-- Shared selection is generated by dots; this adapter never invokes the CLI.
local M = {}
local uv = vim.uv or vim.loop
local last_generation
local reported
local failed_generation
local installed = false
local valid_flavors = { mocha = true, macchiato = true, frappe = true, latte = true }
local required = {
  "rosewater",
  "flamingo",
  "pink",
  "mauve",
  "red",
  "maroon",
  "peach",
  "yellow",
  "green",
  "teal",
  "sky",
  "sapphire",
  "blue",
  "lavender",
  "text",
  "subtext1",
  "subtext0",
  "overlay2",
  "overlay1",
  "overlay0",
  "surface2",
  "surface1",
  "surface0",
  "base",
  "mantle",
  "crust",
}

local function root()
  local state = vim.env.XDG_STATE_HOME
  if not state or state == "" then
    local home = vim.env.HOME or vim.env.USERPROFILE
    if not home then
      return nil
    end
    state = home .. "/.local/state"
  end
  return state .. "/dots/themes"
end

local function read(path, limit)
  local stat = uv.fs_lstat(path)
  if not stat or stat.type ~= "file" or stat.size > limit then
    return nil
  end
  local file = io.open(path, "r")
  if not file then
    return nil
  end
  local data = file:read("*a")
  file:close()
  return data
end

local function selection()
  local state = root()
  if not state or not uv.fs_lstat(state .. "/current") then
    return nil
  end
  local token = read(state .. "/current", 128)
  local generation = token and token:match("^(g%.[%w]+)\n$")
  if not generation then
    error("invalid selection")
  end
  if generation == last_generation then
    return nil
  end
  local payload = read(state .. "/generations/" .. generation .. "/palette.json", 65536)
  local data = payload and vim.json.decode(payload)
  if type(data) ~= "table" or data.schema ~= 1 or data.theme ~= "catppuccin" or not valid_flavors[data.flavor] then
    error("unsupported theme generation")
  end
  if type(data.palette) ~= "table" then
    error("missing palette")
  end
  for _, name in ipairs(required) do
    if type(data.palette[name]) ~= "string" or not data.palette[name]:match("^#%x%x%x%x%x%x$") then
      error("invalid palette color: " .. name)
    end
  end
  return { generation = generation, data = data }
end

local function checked_selection()
  local ok, result = pcall(selection)
  if ok then
    reported = nil
    return result
  end
  if not reported then
    reported = true
    vim.schedule(function()
      vim.notify("dots themes: cannot read shared theme; keeping current colors", vim.log.levels.WARN)
    end)
  end
end

local function merge(opts, selected)
  local data = selected.data
  opts.flavour = data.flavor
  opts.color_overrides = vim.deepcopy(opts.color_overrides or {})
  opts.color_overrides[data.flavor] = vim.tbl_extend("force", opts.color_overrides[data.flavor] or {}, data.palette)
  return opts
end

function M.reload(force)
  if force == true then
    last_generation = nil
    failed_generation = nil
  end
  local selected = checked_selection()
  if not selected or selected.generation == failed_generation then
    return
  end
  local cat = require("catppuccin")
  local old = vim.deepcopy(cat.options)
  local old_scheme = vim.g.colors_name
  local ok = pcall(function()
    cat.setup(merge(vim.deepcopy(old), selected))
    vim.cmd.colorscheme("catppuccin-" .. selected.data.flavor)
  end)
  if ok then
    last_generation = selected.generation
    failed_generation = nil
  else
    failed_generation = selected.generation
    pcall(cat.setup, old)
    if old_scheme then
      pcall(vim.cmd.colorscheme, old_scheme)
    end
    vim.notify("dots themes: could not apply shared theme; restored previous settings", vim.log.levels.WARN)
  end
end

function M.options(opts)
  local selected = checked_selection()
  if selected then
    merge(opts, selected)
    last_generation = selected.generation
  end
  if not installed then
    installed = true
    local group = vim.api.nvim_create_augroup("dots_theme", { clear = true })
    vim.api.nvim_create_autocmd({ "FocusGained", "VimResume" }, { group = group, callback = M.reload })
    vim.api.nvim_create_user_command("DotsThemeReload", function()
      M.reload(true)
    end, { desc = "Reload the shared dots theme" })
  end
  return opts
end

return M
